### ISSUE TITLE
build_tree_item

### ISSUE THREAD

**Issue by raffhan** [michalsn/CodeIgniter-Adjacency-List#7]
not view build_tree_item

**Comment by michalsn** [comment]
Can you elaborate? Because at this moment I have no idea what is the problem.

**Comment by dualhub** [comment]
Hi Michał

Firstly, many thanks for creating this library for CI :-). 

I am also seeing an issue with the build_tree_item helper function when viewing the 'samples' page. Specifically, it is this call:

`<?php echo build_tree_item('languages', 4); ?>`

which produces the following error:

`Fatal error: Maximum execution time of 30 seconds exceeded in /my/path/application/helpers/adjacency_list_helper.php on line 244`

FYI I am using Codeigniter 3.1.11 and PHP 7.4 (tried downgrading to 7.0 and had same issue). 

Any help greatly appreciated.

Jim

**Comment by dualhub** [comment]
Hi again,

I tried downgrading PHP to 5.6 and it works. Any idea how to update this so that it works with PHP 7?

Cheers,

Jim

**Comment by dualhub** [comment]
That fixed it. Thanks mate!
